// data
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCH_HOME_DATA = 'FETCH_HOME_DATA';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const FETCH_SINGLE_POST = 'FETCH_SINGLE_POST';
export const FETCH_SAVED_FOOD = 'FETCH_SAVED_FOOD';
